### PR TITLE
Update framework permissions on listing secrets

### PR DESCRIPTION
**Pull request by zyjjay**
Allow controllers in the framework to list secrets

ref: https://issues.redhat.com/browse/ACM-6869

### CODE REVIEW

**Review by dhaiducek — COMMENTED** [review]
LGTM! But why are we doing a list for a single secret? Is that something from the controller-runtime update?

Also, an aside: Does the framework really need to be updating events? I'd think that'd be a one and done operation (though I could be mistaken...).

**Comment by zyjjay** [comment]
@mprahl done

**Review by dhaiducek — APPROVED** [review]

**Pull request merged**
