### PR TITLE
Set "oldest" tag in Makefile

### PR DESCRIPTION
**Pull request by dhaiducek**

### CODE REVIEW

**Comment by dhaiducek** [comment]
Depends on:
- https://github.com/openshift/release/pull/34349

**Review by JustinKuli — COMMENTED** [review]
/hold

I think I like doing this in the Makefile more than in the github action like I did in this similar thing: https://github.com/open-cluster-management-io/governance-policy-framework-addon/pull/18/commits/ced96c8a4f06b34464ef1ffe3ec4d6ee7a771cb1

But I wonder about using "oldest". The other PR uses "minimum" which I slightly prefer, although neither are perfect.

**Comment by dhaiducek** [comment]
I like "minimum" better--I'll update the PRs.

**Review by gparvin — DISMISSED** [review]

**Review by JustinKuli — APPROVED** [review]

**Pull request merged**
