### PR TITLE
Manage the addon namespace for OpenShift monitoring configuration

### PR DESCRIPTION
**Pull request by mprahl**
Previously, only non-default namespace would get the openshift.io/cluster-monitoring label if Prometheus was enabled and it was OpenShift. Now this also gets set on the default namespace name.

Relates:
https://issues.redhat.com/browse/ACM-7675
https://issues.redhat.com/browse/ACM-7633

### CODE REVIEW

**Comment by yiraeChristineKim** [comment]
Can you ping me after Kind test pass?

**Comment by dhaiducek** [comment]
> Can you ping me after Kind test pass?

These failures looks similar to what https://github.com/open-cluster-management-io/governance-policy-addon-controller/pull/102 is attempting to fix, so hopefully a rebase after that merges will address it.

**Comment by mprahl** [comment]
@yiraeChristineKim, okay it's rebased now.

**Comment by elgnay** [comment]
LGTM

**Review by JustinKuli — APPROVED** [review]

**Pull request merged**
