### PR TITLE
Disable Gatekeeper syncing in hosted mode

### PR DESCRIPTION
**Pull request by dhaiducek**
Depends on:
- https://github.com/open-cluster-management-io/governance-policy-framework-addon/pull/49

### CODE REVIEW

**Review by JustinKuli — DISMISSED** [review]
Are these failures caused by something we're already looking at? (We have a lot of things in the air right now)

**Comment by dhaiducek** [comment]
> Are these failures caused by something we're already looking at? (We have a lot of things in the air right now)

I hadn't noticed it had failed (and I'm kind of surprised it did). Since these aren't framework E2E tests, it sounds like there might be something more here I need to investigate...

**Comment by dhaiducek** [comment]
It's doing some whitespace chomping, and I'll bet it no longer needs to do that with a raw string...

**Comment by dhaiducek** [comment]
Well. It wasn't that. Looks like I have some actually investigating to do!

**Comment by dhaiducek** [comment]
Blocked by:
- #71

**Review by JustinKuli — APPROVED** [review]

**Pull request merged**
